DROP TABLE IF EXISTS peers;

CREATE TABLE peers (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(30) NOT NULL,
    names TEXT NOT NULL,
    password TEXT NOT NULL
);

DROP TABLE IF EXISTS userFiles;
        
CREATE TABLE userFiles (
    userID INTEGER PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    receiver INTEGER NOT NULL,
    fileName TEXT NOT NULL
);

DROP TABLE IF EXISTS myKeys;

CREATE TABLE myKeys (
    userID INTEGER PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userKey TEXT NOT NULL
);   
